[build]
  functions = "functions"

[build.environment]
  NODE_VERSION = "26.0.0"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
