import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage();
const errs = [];
p.on('pageerror', (e) => errs.push(e.message));
p.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
await p.goto('http://localhost:5174/recreation');
await p.waitForSelector('text=IDENTIFY USER', { timeout: 20000 });
await p.keyboard.press('Enter');
await p.waitForTimeout(2500);
const body = await p.textContent('body');
console.log('has GAME LOG:', body.includes('GAME LOG'));
console.log('has SYSTEM FAULT:', body.includes('SYSTEM FAULT'));
console.log('body head:', body.slice(0, 250).replace(/\s+/g, ' '));
console.log('errors:', errs.length ? errs.join('\n---\n') : 'none');
await p.screenshot({ path: '/tmp/termlink-verify/47-recreation-probe.png' });
await b.close();
